### PR TITLE
fix: URLByInvNumber always going to computer with id=1

### LINKED ISSUE #65: url generated by qrcode is always going to computer with id=1
I am using glpi on version 9.4.5 with barcode plugins version 2.4.1
Everything seems to be working fine except from the url generated.
il always point to computer of id=1.
I am  trying to check the file checkItembyInv.php to understand.
it figures out that tsis code is always redirecting to '1' instead of redirectind to computer's Id.
```
include ('../../../inc/includes.php');
Session::checkRight("config", UPDATE);
// To be available when plugin is not activated
Plugin::load('barcode');
Html::header(__('Barcode', 'barcode'), $_SERVER['PHP_SELF'], "config", "plugins");
$itemtype = $_GET['itemtype'];
$item = new $itemtype();
$itemInventoryNumber[] = $_GET['inventoryNumber'];
foreach ($itemInventoryNumber as $key => $value) {
   $item = $item->getFromDBByCrit(['otherserial' => $value]);
   Html::redirect($itemtype::getFormURLWithID($item));
};
Html::footer();
```

### PR DESCRIPTION
**Pull request by flegastelois**
Fix  #65

### CODE REVIEW

File: front/checkItemByInv.php [hunk 1]
```diff
@@ -39,7 +39,10 @@
 $item = new $itemtype();
 $itemInventoryNumber[] = $_GET['inventoryNumber'];
 foreach ($itemInventoryNumber as $key => $value) {
-   $item = $item->getFromDBByCrit(['otherserial' => $value]);
-   Html::redirect($itemtype::getFormURLWithID($item));
+   if ($item->getFromDBByCrit(['otherserial' => $value])) {
+      Html::redirect($item->getFormURLWithID($item->getField('id')));
```
Comment (cedric-anne) [inline front/checkItemByInv.php:43]:
```suggestion
      Html::redirect($item->getFormURLWithID($item->getID()));
```

**Review by cedric-anne — APPROVED** [review]
